import os
import pandas as pd
import numpy as np
import statsmodels.api as sm
import statsmodels.formula.api as smf
from joblib import Parallel, delayed
from lifelines import KaplanMeierFitter
from lifelines.utils import restricted_mean_survival_time


# ---------------------------------------------------------
# 1. DEFINE YOUR MULTIPLE ADES AND TAUS HERE
# ---------------------------------------------------------
ades_config = {
     'pp0_aki_older_iptwapplied_covariatesadjusted': {'event_col': 'adverse_event_YN', 'tau': 4.0, 'rmst_formula': 'rmst_pseudo ~ C(group) + C(sex) + score_sum + C(atrial_fibrillation_YN) + C(cancer_YN) + C(cerebrovascular_disease_YN) + C(chronic_kidney_disease_YN) + C(chronic_liver_disease_YN) + C(chronic_respiratory_disease_YN) + C(coronary_artery_disease_YN) + C(depression_YN) + C(diabetes_mellitus_YN) + C(dyslipidemia_YN) + C(hearing_loss_YN) + C(hemiplegia_YN) + C(hypertension_YN) + C(insomnia_YN) + C(obstructive_sleep_apnea_YN) + C(parkinsons_disease_YN) + C(peptic_ulcer_YN) + C(peripheral_artery_disease_YN) + C(traumatic_head_injury_YN) + C(anti_parkinson_agents_YN) + C(anticoagulant_antiplatelet_YN) + C(antidepressants_YN) + C(antidiabetic_drugs_YN) + C(antihistamines_YN) + C(antipsychotics_YN) + C(antispasmodics_YN) + C(anxiolytics_YN) + C(bladder_antimuscarinics_YN) + C(h2ra_YN) + C(sedative_hypnotics_YN) + C(skeletal_muscle_relaxants_YN) + C(statins_YN)', 'ade_file': 'aki_df_260415.csv', 'iptw_file': 'pp0_older_patients_with_propensity_scores.csv', 'result_file_name': 'pp0_aki_older_iptwapplied_covariatesadjusted'},
     'pp0_mace_older_iptwapplied_covariatesadjusted': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~  C(group) + C(sex) + score_sum + C(atrial_fibrillation_YN) + C(cancer_YN) + C(cerebrovascular_disease_YN) + C(chronic_kidney_disease_YN) + C(chronic_liver_disease_YN) + C(chronic_respiratory_disease_YN) + C(coronary_artery_disease_YN) + C(depression_YN) + C(diabetes_mellitus_YN) + C(dyslipidemia_YN) + C(hearing_loss_YN) + C(hemiplegia_YN) + C(hypertension_YN) + C(insomnia_YN) + C(obstructive_sleep_apnea_YN) + C(parkinsons_disease_YN) + C(peptic_ulcer_YN) + C(peripheral_artery_disease_YN) + C(traumatic_head_injury_YN) + C(anti_parkinson_agents_YN) + C(anticoagulant_antiplatelet_YN) + C(antidepressants_YN) + C(antidiabetic_drugs_YN) + C(antihistamines_YN) + C(antipsychotics_YN) + C(antispasmodics_YN) + C(anxiolytics_YN) + C(bladder_antimuscarinics_YN) + C(h2ra_YN) + C(sedative_hypnotics_YN) + C(skeletal_muscle_relaxants_YN) + C(statins_YN)', 'ade_file': 'mace_df_260415.csv', 'iptw_file': 'pp0_older_patients_with_propensity_scores.csv', 'result_file_name': 'pp0_mace_older_iptwapplied_covariatesadjusted'},
     'pp0_itching_older_iptwapplied_covariatesadjusted': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(group) + C(sex) + score_sum + C(atrial_fibrillation_YN) + C(cancer_YN) + C(cerebrovascular_disease_YN) + C(chronic_kidney_disease_YN) + C(chronic_liver_disease_YN) + C(chronic_respiratory_disease_YN) + C(coronary_artery_disease_YN) + C(depression_YN) + C(diabetes_mellitus_YN) + C(dyslipidemia_YN) + C(hearing_loss_YN) + C(hemiplegia_YN) + C(hypertension_YN) + C(insomnia_YN) + C(obstructive_sleep_apnea_YN) + C(parkinsons_disease_YN) + C(peptic_ulcer_YN) + C(peripheral_artery_disease_YN) + C(traumatic_head_injury_YN) + C(anti_parkinson_agents_YN) + C(anticoagulant_antiplatelet_YN) + C(antidepressants_YN) + C(antidiabetic_drugs_YN) + C(antihistamines_YN) + C(antipsychotics_YN) + C(antispasmodics_YN) + C(anxiolytics_YN) + C(bladder_antimuscarinics_YN) + C(h2ra_YN) + C(sedative_hypnotics_YN) + C(skeletal_muscle_relaxants_YN) + C(statins_YN)', 'ade_file': 'itching_df_260415.csv', 'iptw_file': 'pp0_older_patients_with_propensity_scores.csv', 'result_file_name': 'pp0_itching_older_iptwapplied_covariatesadjusted'},
     'pp0_urticaria_older_iptwapplied_covariatesadjusted': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(group) + C(sex) + score_sum + C(atrial_fibrillation_YN) + C(cancer_YN) + C(cerebrovascular_disease_YN) + C(chronic_kidney_disease_YN) + C(chronic_liver_disease_YN) + C(chronic_respiratory_disease_YN) + C(coronary_artery_disease_YN) + C(depression_YN) + C(diabetes_mellitus_YN) + C(dyslipidemia_YN) + C(hearing_loss_YN) + C(hemiplegia_YN) + C(hypertension_YN) + C(insomnia_YN) + C(obstructive_sleep_apnea_YN) + C(parkinsons_disease_YN) + C(peptic_ulcer_YN) + C(peripheral_artery_disease_YN) + C(traumatic_head_injury_YN) + C(anti_parkinson_agents_YN) + C(anticoagulant_antiplatelet_YN) + C(antidepressants_YN) + C(antidiabetic_drugs_YN) + C(antihistamines_YN) + C(antipsychotics_YN) + C(antispasmodics_YN) + C(anxiolytics_YN) + C(bladder_antimuscarinics_YN) + C(h2ra_YN) + C(sedative_hypnotics_YN) + C(skeletal_muscle_relaxants_YN) + C(statins_YN)', 'ade_file': 'urticaria_df_260415.csv', 'iptw_file': 'pp0_older_patients_with_propensity_scores.csv', 'result_file_name': 'pp0_aki_older_iptwapplied_covariatesadjusted'},
     'pp0_aki_younger_iptwapplied_covariatesadjusted': {'event_col': 'adverse_event_YN', 'tau': 4.0, 'rmst_formula': 'rmst_pseudo ~ C(group) + C(sex) + score_sum + C(atrial_fibrillation_YN) + C(cancer_YN) + C(cerebrovascular_disease_YN) + C(chronic_kidney_disease_YN) + C(chronic_liver_disease_YN) + C(chronic_respiratory_disease_YN) + C(coronary_artery_disease_YN) + C(depression_YN) + C(diabetes_mellitus_YN) + C(dyslipidemia_YN) + C(hearing_loss_YN) + C(hemiplegia_YN) + C(hypertension_YN) + C(insomnia_YN) + C(obstructive_sleep_apnea_YN) + C(parkinsons_disease_YN) + C(peptic_ulcer_YN) + C(peripheral_artery_disease_YN) + C(traumatic_head_injury_YN) + C(anti_parkinson_agents_YN) + C(anticoagulant_antiplatelet_YN) + C(antidepressants_YN) + C(antidiabetic_drugs_YN) + C(antihistamines_YN) + C(antipsychotics_YN) + C(antispasmodics_YN) + C(anxiolytics_YN) + C(bladder_antimuscarinics_YN) + C(h2ra_YN) + C(sedative_hypnotics_YN) + C(skeletal_muscle_relaxants_YN) + C(statins_YN)', 'ade_file': 'aki_df_260415.csv', 'iptw_file': 'pp0_younger_patients_with_propensity_scores.csv', 'result_file_name': 'pp0_aki_younger_iptwapplied_covariatesadjusted'},
     'pp0_mace_younger_iptwapplied_covariatesadjusted': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(group) + C(sex) + score_sum + C(atrial_fibrillation_YN) + C(cancer_YN) + C(cerebrovascular_disease_YN) + C(chronic_kidney_disease_YN) + C(chronic_liver_disease_YN) + C(chronic_respiratory_disease_YN) + C(coronary_artery_disease_YN) + C(depression_YN) + C(diabetes_mellitus_YN) + C(dyslipidemia_YN) + C(hearing_loss_YN) + C(hemiplegia_YN) + C(hypertension_YN) + C(insomnia_YN) + C(obstructive_sleep_apnea_YN) + C(parkinsons_disease_YN) + C(peptic_ulcer_YN) + C(peripheral_artery_disease_YN) + C(traumatic_head_injury_YN) + C(anti_parkinson_agents_YN) + C(anticoagulant_antiplatelet_YN) + C(antidepressants_YN) + C(antidiabetic_drugs_YN) + C(antihistamines_YN) + C(antipsychotics_YN) + C(antispasmodics_YN) + C(anxiolytics_YN) + C(bladder_antimuscarinics_YN) + C(h2ra_YN) + C(sedative_hypnotics_YN) + C(skeletal_muscle_relaxants_YN) + C(statins_YN)', 'ade_file': 'mace_df_260415.csv', 'iptw_file': 'pp0_younger_patients_with_propensity_scores.csv', 'result_file_name': 'pp0_mace_younger_iptwapplied_covariatesadjusted'},
     'pp0_itching_younger_iptwapplied_covariatesadjusted': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(group) + C(sex) + score_sum + C(atrial_fibrillation_YN) + C(cancer_YN) + C(cerebrovascular_disease_YN) + C(chronic_kidney_disease_YN) + C(chronic_liver_disease_YN) + C(chronic_respiratory_disease_YN) + C(coronary_artery_disease_YN) + C(depression_YN) + C(diabetes_mellitus_YN) + C(dyslipidemia_YN) + C(hearing_loss_YN) + C(hemiplegia_YN) + C(hypertension_YN) + C(insomnia_YN) + C(obstructive_sleep_apnea_YN) + C(parkinsons_disease_YN) + C(peptic_ulcer_YN) + C(peripheral_artery_disease_YN) + C(traumatic_head_injury_YN) + C(anti_parkinson_agents_YN) + C(anticoagulant_antiplatelet_YN) + C(antidepressants_YN) + C(antidiabetic_drugs_YN) + C(antihistamines_YN) + C(antipsychotics_YN) + C(antispasmodics_YN) + C(anxiolytics_YN) + C(bladder_antimuscarinics_YN) + C(h2ra_YN) + C(sedative_hypnotics_YN) + C(skeletal_muscle_relaxants_YN) + C(statins_YN)', 'ade_file': 'itching_df_260415.csv', 'iptw_file': 'pp0_younger_patients_with_propensity_scores.csv', 'result_file_name': 'pp0_itching_younger_iptwapplied_covariatesadjusted'},
    'pp0_urticaria_younger_iptwapplied_covariatesadjusted': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(group) + C(sex) + score_sum + C(atrial_fibrillation_YN) + C(cancer_YN) + C(cerebrovascular_disease_YN) + C(chronic_kidney_disease_YN) + C(chronic_liver_disease_YN) + C(chronic_respiratory_disease_YN) + C(coronary_artery_disease_YN) + C(depression_YN) + C(diabetes_mellitus_YN) + C(dyslipidemia_YN) + C(hearing_loss_YN) + C(hemiplegia_YN) + C(hypertension_YN) + C(insomnia_YN) + C(obstructive_sleep_apnea_YN) + C(parkinsons_disease_YN) + C(peptic_ulcer_YN) + C(peripheral_artery_disease_YN) + C(traumatic_head_injury_YN) + C(anti_parkinson_agents_YN) + C(anticoagulant_antiplatelet_YN) + C(antidepressants_YN) + C(antidiabetic_drugs_YN) + C(antihistamines_YN) + C(antipsychotics_YN) + C(antispasmodics_YN) + C(anxiolytics_YN) + C(bladder_antimuscarinics_YN) + C(h2ra_YN) + C(sedative_hypnotics_YN) + C(skeletal_muscle_relaxants_YN) + C(statins_YN)', 'ade_file': 'urticaria_df_260415.csv', 'iptw_file': 'pp0_younger_patients_with_propensity_scores.csv', 'result_file_name': 'pp0_aki_younger_iptwapplied_covariatesadjusted'},
     'pp0_aki_overall_iptwapplied_covariatesadjusted': {'event_col': 'adverse_event_YN', 'tau': 4.0, 'rmst_formula': 'rmst_pseudo ~ C(age_65_YN) * C(group) + C(sex) + score_sum + C(atrial_fibrillation_YN) + C(cancer_YN) + C(cerebrovascular_disease_YN) + C(chronic_kidney_disease_YN) + C(chronic_liver_disease_YN) + C(chronic_respiratory_disease_YN) + C(coronary_artery_disease_YN) + C(depression_YN) + C(diabetes_mellitus_YN) + C(dyslipidemia_YN) + C(hearing_loss_YN) + C(hemiplegia_YN) + C(hypertension_YN) + C(insomnia_YN) + C(obstructive_sleep_apnea_YN) + C(parkinsons_disease_YN) + C(peptic_ulcer_YN) + C(peripheral_artery_disease_YN) + C(traumatic_head_injury_YN) + C(anti_parkinson_agents_YN) + C(anticoagulant_antiplatelet_YN) + C(antidepressants_YN) + C(antidiabetic_drugs_YN) + C(antihistamines_YN) + C(antipsychotics_YN) + C(antispasmodics_YN) + C(anxiolytics_YN) + C(bladder_antimuscarinics_YN) + C(h2ra_YN) + C(sedative_hypnotics_YN) + C(skeletal_muscle_relaxants_YN) + C(statins_YN)', 'ade_file': 'aki_df_260415.csv', 'iptw_file': 'pp0_overall_patients_with_propensity_scores.csv', 'result_file_name': 'pp0_aki_overall_iptwapplied_covariatesadjusted'},
    'pp0_mace_overall_iptwapplied_covariatesadjusted': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(age_65_YN) * C(group) + C(sex) + score_sum + C(atrial_fibrillation_YN) + C(cancer_YN) + C(cerebrovascular_disease_YN) + C(chronic_kidney_disease_YN) + C(chronic_liver_disease_YN) + C(chronic_respiratory_disease_YN) + C(coronary_artery_disease_YN) + C(depression_YN) + C(diabetes_mellitus_YN) + C(dyslipidemia_YN) + C(hearing_loss_YN) + C(hemiplegia_YN) + C(hypertension_YN) + C(insomnia_YN) + C(obstructive_sleep_apnea_YN) + C(parkinsons_disease_YN) + C(peptic_ulcer_YN) + C(peripheral_artery_disease_YN) + C(traumatic_head_injury_YN) + C(anti_parkinson_agents_YN) + C(anticoagulant_antiplatelet_YN) + C(antidepressants_YN) + C(antidiabetic_drugs_YN) + C(antihistamines_YN) + C(antipsychotics_YN) + C(antispasmodics_YN) + C(anxiolytics_YN) + C(bladder_antimuscarinics_YN) + C(h2ra_YN) + C(sedative_hypnotics_YN) + C(skeletal_muscle_relaxants_YN) + C(statins_YN)', 'ade_file': 'mace_df_260415.csv', 'iptw_file': 'pp0_overall_patients_with_propensity_scores.csv', 'result_file_name': 'pp0_mace_overall_iptwapplied_covariatesadjusted'},
     'pp0_itching_overall_iptwapplied_covariatesadjusted': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(age_65_YN) * C(group) + C(sex) + score_sum + C(atrial_fibrillation_YN) + C(cancer_YN) + C(cerebrovascular_disease_YN) + C(chronic_kidney_disease_YN) + C(chronic_liver_disease_YN) + C(chronic_respiratory_disease_YN) + C(coronary_artery_disease_YN) + C(depression_YN) + C(diabetes_mellitus_YN) + C(dyslipidemia_YN) + C(hearing_loss_YN) + C(hemiplegia_YN) + C(hypertension_YN) + C(insomnia_YN) + C(obstructive_sleep_apnea_YN) + C(parkinsons_disease_YN) + C(peptic_ulcer_YN) + C(peripheral_artery_disease_YN) + C(traumatic_head_injury_YN) + C(anti_parkinson_agents_YN) + C(anticoagulant_antiplatelet_YN) + C(antidepressants_YN) + C(antidiabetic_drugs_YN) + C(antihistamines_YN) + C(antipsychotics_YN) + C(antispasmodics_YN) + C(anxiolytics_YN) + C(bladder_antimuscarinics_YN) + C(h2ra_YN) + C(sedative_hypnotics_YN) + C(skeletal_muscle_relaxants_YN) + C(statins_YN)', 'ade_file': 'itching_df_260415.csv', 'iptw_file': 'pp0_overall_patients_with_propensity_scores.csv', 'result_file_name': 'pp0_itching_overall_iptwapplied_covariatesadjusted'},
    'pp0_urticaria_overall_iptwapplied_covariatesadjusted': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(age_65_YN) * C(group) + C(sex) + score_sum + C(atrial_fibrillation_YN) + C(cancer_YN) + C(cerebrovascular_disease_YN) + C(chronic_kidney_disease_YN) + C(chronic_liver_disease_YN) + C(chronic_respiratory_disease_YN) + C(coronary_artery_disease_YN) + C(depression_YN) + C(diabetes_mellitus_YN) + C(dyslipidemia_YN) + C(hearing_loss_YN) + C(hemiplegia_YN) + C(hypertension_YN) + C(insomnia_YN) + C(obstructive_sleep_apnea_YN) + C(parkinsons_disease_YN) + C(peptic_ulcer_YN) + C(peripheral_artery_disease_YN) + C(traumatic_head_injury_YN) + C(anti_parkinson_agents_YN) + C(anticoagulant_antiplatelet_YN) + C(antidepressants_YN) + C(antidiabetic_drugs_YN) + C(antihistamines_YN) + C(antipsychotics_YN) + C(antispasmodics_YN) + C(anxiolytics_YN) + C(bladder_antimuscarinics_YN) + C(h2ra_YN) + C(sedative_hypnotics_YN) + C(skeletal_muscle_relaxants_YN) + C(statins_YN)', 'ade_file': 'urticaria_df_260415.csv', 'iptw_file': 'pp0_overall_patients_with_propensity_scores.csv', 'result_file_name': 'pp0_aki_overall_iptwapplied_covariatesadjusted'},
     'pp0_aki_older_iptwapplied_crude': {'event_col': 'adverse_event_YN', 'tau': 4.0, 'rmst_formula': 'rmst_pseudo ~ C(group)', 'ade_file': 'aki_df_260415.csv', 'iptw_file': 'pp0_older_patients_with_propensity_scores.csv', 'result_file_name': 'pp0_aki_older_iptwapplied_crude'},
    'pp0_mace_older_iptwapplied_crude': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(group)', 'ade_file': 'mace_df_260415.csv', 'iptw_file': 'pp0_older_patients_with_propensity_scores.csv', 'result_file_name': 'pp0_mace_older_iptwapplied_crude'},
     'pp0_itching_older_iptwapplied_crude': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(group)', 'ade_file': 'itching_df_260415.csv', 'iptw_file': 'pp0_older_patients_with_propensity_scores.csv', 'result_file_name': 'pp0_itching_older_iptwapplied_crude'},
    'pp0_urticaria_older_iptwapplied_crude': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(group)', 'ade_file': 'urticaria_df_260415.csv', 'iptw_file': 'pp0_older_patients_with_propensity_scores.csv', 'result_file_name': 'pp0_aki_older_iptwapplied_crude'},
    'pp0_aki_younger_iptwapplied_crude': {'event_col': 'adverse_event_YN', 'tau': 4.0, 'rmst_formula': 'rmst_pseudo ~  C(group)', 'ade_file': 'aki_df_260415.csv', 'iptw_file': 'pp0_younger_patients_with_propensity_scores.csv', 'result_file_name': 'pp0_aki_younger_iptwapplied_crude'},
    'pp0_mace_younger_iptwapplied_crude': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(group)', 'ade_file': 'mace_df_260415.csv', 'iptw_file': 'pp0_younger_patients_with_propensity_scores.csv', 'result_file_name': 'pp0_mace_younger_iptwapplied_crude'},
     'pp0_itching_younger_iptwapplied_crude': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~  C(group)', 'ade_file': 'itching_df_260415.csv', 'iptw_file': 'pp0_younger_patients_with_propensity_scores.csv', 'result_file_name': 'pp0_itching_younger_iptwapplied_crude'},
     'pp0_urticaria_younger_iptwapplied_crude': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(group)', 'ade_file': 'urticaria_df_260415.csv', 'iptw_file': 'pp0_younger_patients_with_propensity_scores.csv', 'result_file_name': 'pp0_aki_younger_iptwapplied_crude'},
    'pp0_aki_overall_iptwapplied_crude': {'event_col': 'adverse_event_YN', 'tau': 4.0, 'rmst_formula': 'rmst_pseudo ~ C(age_65_YN) * C(group)', 'ade_file': 'aki_df_260415.csv', 'iptw_file': 'pp0_overall_patients_with_propensity_scores.csv', 'result_file_name': 'pp0_aki_overall_iptwapplied_crude'},
    'pp0_mace_overall_iptwapplied_crude': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(age_65_YN) * C(group)', 'ade_file': 'mace_df_260415.csv', 'iptw_file': 'pp0_overall_patients_with_propensity_scores.csv', 'result_file_name': 'pp0_mace_overall_iptwapplied_crude'},
     'pp0_itching_overall_iptwapplied_crude': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(age_65_YN) * C(group)', 'ade_file': 'itching_df_260415.csv', 'iptw_file': 'pp0_overall_patients_with_propensity_scores.csv', 'result_file_name': 'pp0_itching_overall_iptwapplied_crude'},
     'pp0_urticaria_overall_iptwapplied_crude': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(age_65_YN) * C(group)', 'ade_file': 'urticaria_df_260415.csv', 'iptw_file': 'pp0_overall_patients_with_propensity_scores.csv', 'result_file_name': 'pp0_aki_overall_iptwapplied_crude'}, 
     'pp1_aki_older_iptwapplied_covariatesadjusted': {'event_col': 'adverse_event_YN', 'tau': 4.0, 'rmst_formula': 'rmst_pseudo ~ C(group) + C(sex) + score_sum + C(atrial_fibrillation_YN) + C(cancer_YN) + C(cerebrovascular_disease_YN) + C(chronic_kidney_disease_YN) + C(chronic_liver_disease_YN) + C(chronic_respiratory_disease_YN) + C(coronary_artery_disease_YN) + C(depression_YN) + C(diabetes_mellitus_YN) + C(dyslipidemia_YN) + C(hearing_loss_YN) + C(hemiplegia_YN) + C(hypertension_YN) + C(insomnia_YN) + C(obstructive_sleep_apnea_YN) + C(parkinsons_disease_YN) + C(peptic_ulcer_YN) + C(peripheral_artery_disease_YN) + C(traumatic_head_injury_YN) + C(anti_parkinson_agents_YN) + C(anticoagulant_antiplatelet_YN) + C(antidepressants_YN) + C(antidiabetic_drugs_YN) + C(antihistamines_YN) + C(antipsychotics_YN) + C(antispasmodics_YN) + C(anxiolytics_YN) + C(bladder_antimuscarinics_YN) + C(h2ra_YN) + C(sedative_hypnotics_YN) + C(skeletal_muscle_relaxants_YN) + C(statins_YN)', 'ade_file': 'aki_df_260415.csv', 'iptw_file': 'pp1_older_patients_with_propensity_scores.csv', 'result_file_name': 'pp1_aki_older_iptwapplied_covariatesadjusted'},
     'pp1_mace_older_iptwapplied_covariatesadjusted': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~  C(group) + C(sex) + score_sum + C(atrial_fibrillation_YN) + C(cancer_YN) + C(cerebrovascular_disease_YN) + C(chronic_kidney_disease_YN) + C(chronic_liver_disease_YN) + C(chronic_respiratory_disease_YN) + C(coronary_artery_disease_YN) + C(depression_YN) + C(diabetes_mellitus_YN) + C(dyslipidemia_YN) + C(hearing_loss_YN) + C(hemiplegia_YN) + C(hypertension_YN) + C(insomnia_YN) + C(obstructive_sleep_apnea_YN) + C(parkinsons_disease_YN) + C(peptic_ulcer_YN) + C(peripheral_artery_disease_YN) + C(traumatic_head_injury_YN) + C(anti_parkinson_agents_YN) + C(anticoagulant_antiplatelet_YN) + C(antidepressants_YN) + C(antidiabetic_drugs_YN) + C(antihistamines_YN) + C(antipsychotics_YN) + C(antispasmodics_YN) + C(anxiolytics_YN) + C(bladder_antimuscarinics_YN) + C(h2ra_YN) + C(sedative_hypnotics_YN) + C(skeletal_muscle_relaxants_YN) + C(statins_YN)', 'ade_file': 'mace_df_260415.csv', 'iptw_file': 'pp1_older_patients_with_propensity_scores.csv', 'result_file_name': 'pp1_mace_older_iptwapplied_covariatesadjusted'},
     'pp1_itching_older_iptwapplied_covariatesadjusted': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(group) + C(sex) + score_sum + C(atrial_fibrillation_YN) + C(cancer_YN) + C(cerebrovascular_disease_YN) + C(chronic_kidney_disease_YN) + C(chronic_liver_disease_YN) + C(chronic_respiratory_disease_YN) + C(coronary_artery_disease_YN) + C(depression_YN) + C(diabetes_mellitus_YN) + C(dyslipidemia_YN) + C(hearing_loss_YN) + C(hemiplegia_YN) + C(hypertension_YN) + C(insomnia_YN) + C(obstructive_sleep_apnea_YN) + C(parkinsons_disease_YN) + C(peptic_ulcer_YN) + C(peripheral_artery_disease_YN) + C(traumatic_head_injury_YN) + C(anti_parkinson_agents_YN) + C(anticoagulant_antiplatelet_YN) + C(antidepressants_YN) + C(antidiabetic_drugs_YN) + C(antihistamines_YN) + C(antipsychotics_YN) + C(antispasmodics_YN) + C(anxiolytics_YN) + C(bladder_antimuscarinics_YN) + C(h2ra_YN) + C(sedative_hypnotics_YN) + C(skeletal_muscle_relaxants_YN) + C(statins_YN)', 'ade_file': 'itching_df_260415.csv', 'iptw_file': 'pp1_older_patients_with_propensity_scores.csv', 'result_file_name': 'pp1_itching_older_iptwapplied_covariatesadjusted'},
    'pp1_urticaria_older_iptwapplied_covariatesadjusted': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(group) + C(sex) + score_sum + C(atrial_fibrillation_YN) + C(cancer_YN) + C(cerebrovascular_disease_YN) + C(chronic_kidney_disease_YN) + C(chronic_liver_disease_YN) + C(chronic_respiratory_disease_YN) + C(coronary_artery_disease_YN) + C(depression_YN) + C(diabetes_mellitus_YN) + C(dyslipidemia_YN) + C(hearing_loss_YN) + C(hemiplegia_YN) + C(hypertension_YN) + C(insomnia_YN) + C(obstructive_sleep_apnea_YN) + C(parkinsons_disease_YN) + C(peptic_ulcer_YN) + C(peripheral_artery_disease_YN) + C(traumatic_head_injury_YN) + C(anti_parkinson_agents_YN) + C(anticoagulant_antiplatelet_YN) + C(antidepressants_YN) + C(antidiabetic_drugs_YN) + C(antihistamines_YN) + C(antipsychotics_YN) + C(antispasmodics_YN) + C(anxiolytics_YN) + C(bladder_antimuscarinics_YN) + C(h2ra_YN) + C(sedative_hypnotics_YN) + C(skeletal_muscle_relaxants_YN) + C(statins_YN)', 'ade_file': 'urticaria_df_260415.csv', 'iptw_file': 'pp1_older_patients_with_propensity_scores.csv', 'result_file_name': 'pp1_aki_older_iptwapplied_covariatesadjusted'},
     'pp1_aki_younger_iptwapplied_covariatesadjusted': {'event_col': 'adverse_event_YN', 'tau': 4.0, 'rmst_formula': 'rmst_pseudo ~ C(group) + C(sex) + score_sum + C(atrial_fibrillation_YN) + C(cancer_YN) + C(cerebrovascular_disease_YN) + C(chronic_kidney_disease_YN) + C(chronic_liver_disease_YN) + C(chronic_respiratory_disease_YN) + C(coronary_artery_disease_YN) + C(depression_YN) + C(diabetes_mellitus_YN) + C(dyslipidemia_YN) + C(hearing_loss_YN) + C(hemiplegia_YN) + C(hypertension_YN) + C(insomnia_YN) + C(obstructive_sleep_apnea_YN) + C(parkinsons_disease_YN) + C(peptic_ulcer_YN) + C(peripheral_artery_disease_YN) + C(traumatic_head_injury_YN) + C(anti_parkinson_agents_YN) + C(anticoagulant_antiplatelet_YN) + C(antidepressants_YN) + C(antidiabetic_drugs_YN) + C(antihistamines_YN) + C(antipsychotics_YN) + C(antispasmodics_YN) + C(anxiolytics_YN) + C(bladder_antimuscarinics_YN) + C(h2ra_YN) + C(sedative_hypnotics_YN) + C(skeletal_muscle_relaxants_YN) + C(statins_YN)', 'ade_file': 'aki_df_260415.csv', 'iptw_file': 'pp1_younger_patients_with_propensity_scores.csv', 'result_file_name': 'pp1_aki_younger_iptwapplied_covariatesadjusted'},
     'pp1_mace_younger_iptwapplied_covariatesadjusted': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(group) + C(sex) + score_sum + C(atrial_fibrillation_YN) + C(cancer_YN) + C(cerebrovascular_disease_YN) + C(chronic_kidney_disease_YN) + C(chronic_liver_disease_YN) + C(chronic_respiratory_disease_YN) + C(coronary_artery_disease_YN) + C(depression_YN) + C(diabetes_mellitus_YN) + C(dyslipidemia_YN) + C(hearing_loss_YN) + C(hemiplegia_YN) + C(hypertension_YN) + C(insomnia_YN) + C(obstructive_sleep_apnea_YN) + C(parkinsons_disease_YN) + C(peptic_ulcer_YN) + C(peripheral_artery_disease_YN) + C(traumatic_head_injury_YN) + C(anti_parkinson_agents_YN) + C(anticoagulant_antiplatelet_YN) + C(antidepressants_YN) + C(antidiabetic_drugs_YN) + C(antihistamines_YN) + C(antipsychotics_YN) + C(antispasmodics_YN) + C(anxiolytics_YN) + C(bladder_antimuscarinics_YN) + C(h2ra_YN) + C(sedative_hypnotics_YN) + C(skeletal_muscle_relaxants_YN) + C(statins_YN)', 'ade_file': 'mace_df_260415.csv', 'iptw_file': 'pp1_younger_patients_with_propensity_scores.csv', 'result_file_name': 'pp1_mace_younger_iptwapplied_covariatesadjusted'},
     'pp1_itching_younger_iptwapplied_covariatesadjusted': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(group) + C(sex) + score_sum + C(atrial_fibrillation_YN) + C(cancer_YN) + C(cerebrovascular_disease_YN) + C(chronic_kidney_disease_YN) + C(chronic_liver_disease_YN) + C(chronic_respiratory_disease_YN) + C(coronary_artery_disease_YN) + C(depression_YN) + C(diabetes_mellitus_YN) + C(dyslipidemia_YN) + C(hearing_loss_YN) + C(hemiplegia_YN) + C(hypertension_YN) + C(insomnia_YN) + C(obstructive_sleep_apnea_YN) + C(parkinsons_disease_YN) + C(peptic_ulcer_YN) + C(peripheral_artery_disease_YN) + C(traumatic_head_injury_YN) + C(anti_parkinson_agents_YN) + C(anticoagulant_antiplatelet_YN) + C(antidepressants_YN) + C(antidiabetic_drugs_YN) + C(antihistamines_YN) + C(antipsychotics_YN) + C(antispasmodics_YN) + C(anxiolytics_YN) + C(bladder_antimuscarinics_YN) + C(h2ra_YN) + C(sedative_hypnotics_YN) + C(skeletal_muscle_relaxants_YN) + C(statins_YN)', 'ade_file': 'itching_df_260415.csv', 'iptw_file': 'pp1_younger_patients_with_propensity_scores.csv', 'result_file_name': 'pp1_itching_younger_iptwapplied_covariatesadjusted'},
    'pp1_urticaria_younger_iptwapplied_covariatesadjusted': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(group) + C(sex) + score_sum + C(atrial_fibrillation_YN) + C(cancer_YN) + C(cerebrovascular_disease_YN) + C(chronic_kidney_disease_YN) + C(chronic_liver_disease_YN) + C(chronic_respiratory_disease_YN) + C(coronary_artery_disease_YN) + C(depression_YN) + C(diabetes_mellitus_YN) + C(dyslipidemia_YN) + C(hearing_loss_YN) + C(hemiplegia_YN) + C(hypertension_YN) + C(insomnia_YN) + C(obstructive_sleep_apnea_YN) + C(parkinsons_disease_YN) + C(peptic_ulcer_YN) + C(peripheral_artery_disease_YN) + C(traumatic_head_injury_YN) + C(anti_parkinson_agents_YN) + C(anticoagulant_antiplatelet_YN) + C(antidepressants_YN) + C(antidiabetic_drugs_YN) + C(antihistamines_YN) + C(antipsychotics_YN) + C(antispasmodics_YN) + C(anxiolytics_YN) + C(bladder_antimuscarinics_YN) + C(h2ra_YN) + C(sedative_hypnotics_YN) + C(skeletal_muscle_relaxants_YN) + C(statins_YN)', 'ade_file': 'urticaria_df_260415.csv', 'iptw_file': 'pp1_younger_patients_with_propensity_scores.csv', 'result_file_name': 'pp1_aki_younger_iptwapplied_covariatesadjusted'},
     'pp1_aki_overall_iptwapplied_covariatesadjusted': {'event_col': 'adverse_event_YN', 'tau': 4.0, 'rmst_formula': 'rmst_pseudo ~ C(age_65_YN) * C(group) + C(sex) + score_sum + C(atrial_fibrillation_YN) + C(cancer_YN) + C(cerebrovascular_disease_YN) + C(chronic_kidney_disease_YN) + C(chronic_liver_disease_YN) + C(chronic_respiratory_disease_YN) + C(coronary_artery_disease_YN) + C(depression_YN) + C(diabetes_mellitus_YN) + C(dyslipidemia_YN) + C(hearing_loss_YN) + C(hemiplegia_YN) + C(hypertension_YN) + C(insomnia_YN) + C(obstructive_sleep_apnea_YN) + C(parkinsons_disease_YN) + C(peptic_ulcer_YN) + C(peripheral_artery_disease_YN) + C(traumatic_head_injury_YN) + C(anti_parkinson_agents_YN) + C(anticoagulant_antiplatelet_YN) + C(antidepressants_YN) + C(antidiabetic_drugs_YN) + C(antihistamines_YN) + C(antipsychotics_YN) + C(antispasmodics_YN) + C(anxiolytics_YN) + C(bladder_antimuscarinics_YN) + C(h2ra_YN) + C(sedative_hypnotics_YN) + C(skeletal_muscle_relaxants_YN) + C(statins_YN)', 'ade_file': 'aki_df_260415.csv', 'iptw_file': 'pp1_overall_patients_with_propensity_scores.csv', 'result_file_name': 'pp1_aki_overall_iptwapplied_covariatesadjusted'},
     'pp1_mace_overall_iptwapplied_covariatesadjusted': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(age_65_YN) * C(group) + C(sex) + score_sum + C(atrial_fibrillation_YN) + C(cancer_YN) + C(cerebrovascular_disease_YN) + C(chronic_kidney_disease_YN) + C(chronic_liver_disease_YN) + C(chronic_respiratory_disease_YN) + C(coronary_artery_disease_YN) + C(depression_YN) + C(diabetes_mellitus_YN) + C(dyslipidemia_YN) + C(hearing_loss_YN) + C(hemiplegia_YN) + C(hypertension_YN) + C(insomnia_YN) + C(obstructive_sleep_apnea_YN) + C(parkinsons_disease_YN) + C(peptic_ulcer_YN) + C(peripheral_artery_disease_YN) + C(traumatic_head_injury_YN) + C(anti_parkinson_agents_YN) + C(anticoagulant_antiplatelet_YN) + C(antidepressants_YN) + C(antidiabetic_drugs_YN) + C(antihistamines_YN) + C(antipsychotics_YN) + C(antispasmodics_YN) + C(anxiolytics_YN) + C(bladder_antimuscarinics_YN) + C(h2ra_YN) + C(sedative_hypnotics_YN) + C(skeletal_muscle_relaxants_YN) + C(statins_YN)', 'ade_file': 'mace_df_260415.csv', 'iptw_file': 'pp1_overall_patients_with_propensity_scores.csv', 'result_file_name': 'pp1_mace_overall_iptwapplied_covariatesadjusted'},
     'pp1_itching_overall_iptwapplied_covariatesadjusted': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(age_65_YN) * C(group) + C(sex) + score_sum + C(atrial_fibrillation_YN) + C(cancer_YN) + C(cerebrovascular_disease_YN) + C(chronic_kidney_disease_YN) + C(chronic_liver_disease_YN) + C(chronic_respiratory_disease_YN) + C(coronary_artery_disease_YN) + C(depression_YN) + C(diabetes_mellitus_YN) + C(dyslipidemia_YN) + C(hearing_loss_YN) + C(hemiplegia_YN) + C(hypertension_YN) + C(insomnia_YN) + C(obstructive_sleep_apnea_YN) + C(parkinsons_disease_YN) + C(peptic_ulcer_YN) + C(peripheral_artery_disease_YN) + C(traumatic_head_injury_YN) + C(anti_parkinson_agents_YN) + C(anticoagulant_antiplatelet_YN) + C(antidepressants_YN) + C(antidiabetic_drugs_YN) + C(antihistamines_YN) + C(antipsychotics_YN) + C(antispasmodics_YN) + C(anxiolytics_YN) + C(bladder_antimuscarinics_YN) + C(h2ra_YN) + C(sedative_hypnotics_YN) + C(skeletal_muscle_relaxants_YN) + C(statins_YN)', 'ade_file': 'itching_df_260415.csv', 'iptw_file': 'pp1_overall_patients_with_propensity_scores.csv', 'result_file_name': 'pp1_itching_overall_iptwapplied_covariatesadjusted'},
    'pp1_urticaria_overall_iptwapplied_covariatesadjusted': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(age_65_YN) * C(group) + C(sex) + score_sum + C(atrial_fibrillation_YN) + C(cancer_YN) + C(cerebrovascular_disease_YN) + C(chronic_kidney_disease_YN) + C(chronic_liver_disease_YN) + C(chronic_respiratory_disease_YN) + C(coronary_artery_disease_YN) + C(depression_YN) + C(diabetes_mellitus_YN) + C(dyslipidemia_YN) + C(hearing_loss_YN) + C(hemiplegia_YN) + C(hypertension_YN) + C(insomnia_YN) + C(obstructive_sleep_apnea_YN) + C(parkinsons_disease_YN) + C(peptic_ulcer_YN) + C(peripheral_artery_disease_YN) + C(traumatic_head_injury_YN) + C(anti_parkinson_agents_YN) + C(anticoagulant_antiplatelet_YN) + C(antidepressants_YN) + C(antidiabetic_drugs_YN) + C(antihistamines_YN) + C(antipsychotics_YN) + C(antispasmodics_YN) + C(anxiolytics_YN) + C(bladder_antimuscarinics_YN) + C(h2ra_YN) + C(sedative_hypnotics_YN) + C(skeletal_muscle_relaxants_YN) + C(statins_YN)', 'ade_file': 'urticaria_df_260415.csv', 'iptw_file': 'pp1_overall_patients_with_propensity_scores.csv', 'result_file_name': 'pp1_aki_overall_iptwapplied_covariatesadjusted'},
    'pp1_aki_older_iptwapplied_crude': {'event_col': 'adverse_event_YN', 'tau': 4.0, 'rmst_formula': 'rmst_pseudo ~ C(group)', 'ade_file': 'aki_df_260415.csv', 'iptw_file': 'pp1_older_patients_with_propensity_scores.csv', 'result_file_name': 'pp1_aki_older_iptwapplied_crude'},
     'pp1_mace_older_iptwapplied_crude': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(group)', 'ade_file': 'mace_df_260415.csv', 'iptw_file': 'pp1_older_patients_with_propensity_scores.csv', 'result_file_name': 'pp1_mace_older_iptwapplied_crude'},
     'pp1_itching_older_iptwapplied_crude': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(group)', 'ade_file': 'itching_df_260415.csv', 'iptw_file': 'pp1_older_patients_with_propensity_scores.csv', 'result_file_name': 'pp1_itching_older_iptwapplied_crude'},
     'pp1_urticaria_older_iptwapplied_crude': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(group)', 'ade_file': 'urticaria_df_260415.csv', 'iptw_file': 'pp1_older_patients_with_propensity_scores.csv', 'result_file_name': 'pp1_aki_older_iptwapplied_crude'},
     'pp1_aki_younger_iptwapplied_crude': {'event_col': 'adverse_event_YN', 'tau': 4.0, 'rmst_formula': 'rmst_pseudo ~  C(group)', 'ade_file': 'aki_df_260415.csv', 'iptw_file': 'pp1_younger_patients_with_propensity_scores.csv', 'result_file_name': 'pp1_aki_younger_iptwapplied_crude'},
     'pp1_mace_younger_iptwapplied_crude': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(group)', 'ade_file': 'mace_df_260415.csv', 'iptw_file': 'pp1_younger_patients_with_propensity_scores.csv', 'result_file_name': 'pp1_mace_younger_iptwapplied_crude'},
     'pp1_itching_younger_iptwapplied_crude': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~  C(group)', 'ade_file': 'itching_df_260415.csv', 'iptw_file': 'pp1_younger_patients_with_propensity_scores.csv', 'result_file_name': 'pp1_itching_younger_iptwapplied_crude'},
    'pp1_urticaria_younger_iptwapplied_crude': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(group)', 'ade_file': 'urticaria_df_260415.csv', 'iptw_file': 'pp1_younger_patients_with_propensity_scores.csv', 'result_file_name': 'pp1_aki_younger_iptwapplied_crude'},
     'pp1_aki_overall_iptwapplied_crude': {'event_col': 'adverse_event_YN', 'tau': 4.0, 'rmst_formula': 'rmst_pseudo ~ C(age_65_YN) * C(group)', 'ade_file': 'aki_df_260415.csv', 'iptw_file': 'pp1_overall_patients_with_propensity_scores.csv', 'result_file_name': 'pp1_aki_overall_iptwapplied_crude'},
     'pp1_mace_overall_iptwapplied_crude': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(age_65_YN) * C(group)', 'ade_file': 'mace_df_260415.csv', 'iptw_file': 'pp1_overall_patients_with_propensity_scores.csv', 'result_file_name': 'pp1_mace_overall_iptwapplied_crude'},
     'pp1_itching_overall_iptwapplied_crude': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(age_65_YN) * C(group)', 'ade_file': 'itching_df_260415.csv', 'iptw_file': 'pp1_overall_patients_with_propensity_scores.csv', 'result_file_name': 'pp1_itching_overall_iptwapplied_crude'},
    'pp1_urticaria_overall_iptwapplied_crude': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(age_65_YN) * C(group)', 'ade_file': 'urticaria_df_260415.csv', 'iptw_file': 'pp1_overall_patients_with_propensity_scores.csv', 'result_file_name': 'pp1_aki_overall_iptwapplied_crude'}, 
     'pp2_aki_older_iptwapplied_covariatesadjusted': {'event_col': 'adverse_event_YN', 'tau': 4.0, 'rmst_formula': 'rmst_pseudo ~ C(group) + C(sex) + score_sum + C(atrial_fibrillation_YN) + C(cancer_YN) + C(cerebrovascular_disease_YN) + C(chronic_kidney_disease_YN) + C(chronic_liver_disease_YN) + C(chronic_respiratory_disease_YN) + C(coronary_artery_disease_YN) + C(depression_YN) + C(diabetes_mellitus_YN) + C(dyslipidemia_YN) + C(hearing_loss_YN) + C(hemiplegia_YN) + C(hypertension_YN) + C(insomnia_YN) + C(obstructive_sleep_apnea_YN) + C(parkinsons_disease_YN) + C(peptic_ulcer_YN) + C(peripheral_artery_disease_YN) + C(traumatic_head_injury_YN) + C(anti_parkinson_agents_YN) + C(anticoagulant_antiplatelet_YN) + C(antidepressants_YN) + C(antidiabetic_drugs_YN) + C(antihistamines_YN) + C(antipsychotics_YN) + C(antispasmodics_YN) + C(anxiolytics_YN) + C(bladder_antimuscarinics_YN) + C(h2ra_YN) + C(sedative_hypnotics_YN) + C(skeletal_muscle_relaxants_YN) + C(statins_YN)', 'ade_file': 'aki_df_260415.csv', 'iptw_file': 'pp2_older_patients_with_propensity_scores.csv', 'result_file_name': 'pp2_aki_older_iptwapplied_covariatesadjusted'},
    'pp2_mace_older_iptwapplied_covariatesadjusted': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~  C(group) + C(sex) + score_sum + C(atrial_fibrillation_YN) + C(cancer_YN) + C(cerebrovascular_disease_YN) + C(chronic_kidney_disease_YN) + C(chronic_liver_disease_YN) + C(chronic_respiratory_disease_YN) + C(coronary_artery_disease_YN) + C(depression_YN) + C(diabetes_mellitus_YN) + C(dyslipidemia_YN) + C(hearing_loss_YN) + C(hemiplegia_YN) + C(hypertension_YN) + C(insomnia_YN) + C(obstructive_sleep_apnea_YN) + C(parkinsons_disease_YN) + C(peptic_ulcer_YN) + C(peripheral_artery_disease_YN) + C(traumatic_head_injury_YN) + C(anti_parkinson_agents_YN) + C(anticoagulant_antiplatelet_YN) + C(antidepressants_YN) + C(antidiabetic_drugs_YN) + C(antihistamines_YN) + C(antipsychotics_YN) + C(antispasmodics_YN) + C(anxiolytics_YN) + C(bladder_antimuscarinics_YN) + C(h2ra_YN) + C(sedative_hypnotics_YN) + C(skeletal_muscle_relaxants_YN) + C(statins_YN)', 'ade_file': 'mace_df_260415.csv', 'iptw_file': 'pp2_older_patients_with_propensity_scores.csv', 'result_file_name': 'pp2_mace_older_iptwapplied_covariatesadjusted'},
     'pp2_itching_older_iptwapplied_covariatesadjusted': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(group) + C(sex) + score_sum + C(atrial_fibrillation_YN) + C(cancer_YN) + C(cerebrovascular_disease_YN) + C(chronic_kidney_disease_YN) + C(chronic_liver_disease_YN) + C(chronic_respiratory_disease_YN) + C(coronary_artery_disease_YN) + C(depression_YN) + C(diabetes_mellitus_YN) + C(dyslipidemia_YN) + C(hearing_loss_YN) + C(hemiplegia_YN) + C(hypertension_YN) + C(insomnia_YN) + C(obstructive_sleep_apnea_YN) + C(parkinsons_disease_YN) + C(peptic_ulcer_YN) + C(peripheral_artery_disease_YN) + C(traumatic_head_injury_YN) + C(anti_parkinson_agents_YN) + C(anticoagulant_antiplatelet_YN) + C(antidepressants_YN) + C(antidiabetic_drugs_YN) + C(antihistamines_YN) + C(antipsychotics_YN) + C(antispasmodics_YN) + C(anxiolytics_YN) + C(bladder_antimuscarinics_YN) + C(h2ra_YN) + C(sedative_hypnotics_YN) + C(skeletal_muscle_relaxants_YN) + C(statins_YN)', 'ade_file': 'itching_df_260415.csv', 'iptw_file': 'pp2_older_patients_with_propensity_scores.csv', 'result_file_name': 'pp2_itching_older_iptwapplied_covariatesadjusted'},
     'pp2_urticaria_older_iptwapplied_covariatesadjusted': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(group) + C(sex) + score_sum + C(atrial_fibrillation_YN) + C(cancer_YN) + C(cerebrovascular_disease_YN) + C(chronic_kidney_disease_YN) + C(chronic_liver_disease_YN) + C(chronic_respiratory_disease_YN) + C(coronary_artery_disease_YN) + C(depression_YN) + C(diabetes_mellitus_YN) + C(dyslipidemia_YN) + C(hearing_loss_YN) + C(hemiplegia_YN) + C(hypertension_YN) + C(insomnia_YN) + C(obstructive_sleep_apnea_YN) + C(parkinsons_disease_YN) + C(peptic_ulcer_YN) + C(peripheral_artery_disease_YN) + C(traumatic_head_injury_YN) + C(anti_parkinson_agents_YN) + C(anticoagulant_antiplatelet_YN) + C(antidepressants_YN) + C(antidiabetic_drugs_YN) + C(antihistamines_YN) + C(antipsychotics_YN) + C(antispasmodics_YN) + C(anxiolytics_YN) + C(bladder_antimuscarinics_YN) + C(h2ra_YN) + C(sedative_hypnotics_YN) + C(skeletal_muscle_relaxants_YN) + C(statins_YN)', 'ade_file': 'urticaria_df_260415.csv', 'iptw_file': 'pp2_older_patients_with_propensity_scores.csv', 'result_file_name': 'pp2_aki_older_iptwapplied_covariatesadjusted'},
     'pp2_aki_younger_iptwapplied_covariatesadjusted': {'event_col': 'adverse_event_YN', 'tau': 4.0, 'rmst_formula': 'rmst_pseudo ~ C(group) + C(sex) + score_sum + C(atrial_fibrillation_YN) + C(cancer_YN) + C(cerebrovascular_disease_YN) + C(chronic_kidney_disease_YN) + C(chronic_liver_disease_YN) + C(chronic_respiratory_disease_YN) + C(coronary_artery_disease_YN) + C(depression_YN) + C(diabetes_mellitus_YN) + C(dyslipidemia_YN) + C(hearing_loss_YN) + C(hemiplegia_YN) + C(hypertension_YN) + C(insomnia_YN) + C(obstructive_sleep_apnea_YN) + C(parkinsons_disease_YN) + C(peptic_ulcer_YN) + C(peripheral_artery_disease_YN) + C(traumatic_head_injury_YN) + C(anti_parkinson_agents_YN) + C(anticoagulant_antiplatelet_YN) + C(antidepressants_YN) + C(antidiabetic_drugs_YN) + C(antihistamines_YN) + C(antipsychotics_YN) + C(antispasmodics_YN) + C(anxiolytics_YN) + C(bladder_antimuscarinics_YN) + C(h2ra_YN) + C(sedative_hypnotics_YN) + C(skeletal_muscle_relaxants_YN) + C(statins_YN)', 'ade_file': 'aki_df_260415.csv', 'iptw_file': 'pp2_younger_patients_with_propensity_scores.csv', 'result_file_name': 'pp2_aki_younger_iptwapplied_covariatesadjusted'},
    'pp2_mace_younger_iptwapplied_covariatesadjusted': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(group) + C(sex) + score_sum + C(atrial_fibrillation_YN) + C(cancer_YN) + C(cerebrovascular_disease_YN) + C(chronic_kidney_disease_YN) + C(chronic_liver_disease_YN) + C(chronic_respiratory_disease_YN) + C(coronary_artery_disease_YN) + C(depression_YN) + C(diabetes_mellitus_YN) + C(dyslipidemia_YN) + C(hearing_loss_YN) + C(hemiplegia_YN) + C(hypertension_YN) + C(insomnia_YN) + C(obstructive_sleep_apnea_YN) + C(parkinsons_disease_YN) + C(peptic_ulcer_YN) + C(peripheral_artery_disease_YN) + C(traumatic_head_injury_YN) + C(anti_parkinson_agents_YN) + C(anticoagulant_antiplatelet_YN) + C(antidepressants_YN) + C(antidiabetic_drugs_YN) + C(antihistamines_YN) + C(antipsychotics_YN) + C(antispasmodics_YN) + C(anxiolytics_YN) + C(bladder_antimuscarinics_YN) + C(h2ra_YN) + C(sedative_hypnotics_YN) + C(skeletal_muscle_relaxants_YN) + C(statins_YN)', 'ade_file': 'mace_df_260415.csv', 'iptw_file': 'pp2_younger_patients_with_propensity_scores.csv', 'result_file_name': 'pp2_mace_younger_iptwapplied_covariatesadjusted'},
     'pp2_itching_younger_iptwapplied_covariatesadjusted': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(group) + C(sex) + score_sum + C(atrial_fibrillation_YN) + C(cancer_YN) + C(cerebrovascular_disease_YN) + C(chronic_kidney_disease_YN) + C(chronic_liver_disease_YN) + C(chronic_respiratory_disease_YN) + C(coronary_artery_disease_YN) + C(depression_YN) + C(diabetes_mellitus_YN) + C(dyslipidemia_YN) + C(hearing_loss_YN) + C(hemiplegia_YN) + C(hypertension_YN) + C(insomnia_YN) + C(obstructive_sleep_apnea_YN) + C(parkinsons_disease_YN) + C(peptic_ulcer_YN) + C(peripheral_artery_disease_YN) + C(traumatic_head_injury_YN) + C(anti_parkinson_agents_YN) + C(anticoagulant_antiplatelet_YN) + C(antidepressants_YN) + C(antidiabetic_drugs_YN) + C(antihistamines_YN) + C(antipsychotics_YN) + C(antispasmodics_YN) + C(anxiolytics_YN) + C(bladder_antimuscarinics_YN) + C(h2ra_YN) + C(sedative_hypnotics_YN) + C(skeletal_muscle_relaxants_YN) + C(statins_YN)', 'ade_file': 'itching_df_260415.csv', 'iptw_file': 'pp2_younger_patients_with_propensity_scores.csv', 'result_file_name': 'pp2_itching_younger_iptwapplied_covariatesadjusted'},
    'pp2_urticaria_younger_iptwapplied_covariatesadjusted': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(group) + C(sex) + score_sum + C(atrial_fibrillation_YN) + C(cancer_YN) + C(cerebrovascular_disease_YN) + C(chronic_kidney_disease_YN) + C(chronic_liver_disease_YN) + C(chronic_respiratory_disease_YN) + C(coronary_artery_disease_YN) + C(depression_YN) + C(diabetes_mellitus_YN) + C(dyslipidemia_YN) + C(hearing_loss_YN) + C(hemiplegia_YN) + C(hypertension_YN) + C(insomnia_YN) + C(obstructive_sleep_apnea_YN) + C(parkinsons_disease_YN) + C(peptic_ulcer_YN) + C(peripheral_artery_disease_YN) + C(traumatic_head_injury_YN) + C(anti_parkinson_agents_YN) + C(anticoagulant_antiplatelet_YN) + C(antidepressants_YN) + C(antidiabetic_drugs_YN) + C(antihistamines_YN) + C(antipsychotics_YN) + C(antispasmodics_YN) + C(anxiolytics_YN) + C(bladder_antimuscarinics_YN) + C(h2ra_YN) + C(sedative_hypnotics_YN) + C(skeletal_muscle_relaxants_YN) + C(statins_YN)', 'ade_file': 'urticaria_df_260415.csv', 'iptw_file': 'pp2_younger_patients_with_propensity_scores.csv', 'result_file_name': 'pp2_aki_younger_iptwapplied_covariatesadjusted'},
    'pp2_aki_overall_iptwapplied_covariatesadjusted': {'event_col': 'adverse_event_YN', 'tau': 4.0, 'rmst_formula': 'rmst_pseudo ~ C(age_65_YN) * C(group) + C(sex) + score_sum + C(atrial_fibrillation_YN) + C(cancer_YN) + C(cerebrovascular_disease_YN) + C(chronic_kidney_disease_YN) + C(chronic_liver_disease_YN) + C(chronic_respiratory_disease_YN) + C(coronary_artery_disease_YN) + C(depression_YN) + C(diabetes_mellitus_YN) + C(dyslipidemia_YN) + C(hearing_loss_YN) + C(hemiplegia_YN) + C(hypertension_YN) + C(insomnia_YN) + C(obstructive_sleep_apnea_YN) + C(parkinsons_disease_YN) + C(peptic_ulcer_YN) + C(peripheral_artery_disease_YN) + C(traumatic_head_injury_YN) + C(anti_parkinson_agents_YN) + C(anticoagulant_antiplatelet_YN) + C(antidepressants_YN) + C(antidiabetic_drugs_YN) + C(antihistamines_YN) + C(antipsychotics_YN) + C(antispasmodics_YN) + C(anxiolytics_YN) + C(bladder_antimuscarinics_YN) + C(h2ra_YN) + C(sedative_hypnotics_YN) + C(skeletal_muscle_relaxants_YN) + C(statins_YN)', 'ade_file': 'aki_df_260415.csv', 'iptw_file': 'pp2_overall_patients_with_propensity_scores.csv', 'result_file_name': 'pp2_aki_overall_iptwapplied_covariatesadjusted'},
     'pp2_mace_overall_iptwapplied_covariatesadjusted': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(age_65_YN) * C(group) + C(sex) + score_sum + C(atrial_fibrillation_YN) + C(cancer_YN) + C(cerebrovascular_disease_YN) + C(chronic_kidney_disease_YN) + C(chronic_liver_disease_YN) + C(chronic_respiratory_disease_YN) + C(coronary_artery_disease_YN) + C(depression_YN) + C(diabetes_mellitus_YN) + C(dyslipidemia_YN) + C(hearing_loss_YN) + C(hemiplegia_YN) + C(hypertension_YN) + C(insomnia_YN) + C(obstructive_sleep_apnea_YN) + C(parkinsons_disease_YN) + C(peptic_ulcer_YN) + C(peripheral_artery_disease_YN) + C(traumatic_head_injury_YN) + C(anti_parkinson_agents_YN) + C(anticoagulant_antiplatelet_YN) + C(antidepressants_YN) + C(antidiabetic_drugs_YN) + C(antihistamines_YN) + C(antipsychotics_YN) + C(antispasmodics_YN) + C(anxiolytics_YN) + C(bladder_antimuscarinics_YN) + C(h2ra_YN) + C(sedative_hypnotics_YN) + C(skeletal_muscle_relaxants_YN) + C(statins_YN)', 'ade_file': 'mace_df_260415.csv', 'iptw_file': 'pp2_overall_patients_with_propensity_scores.csv', 'result_file_name': 'pp2_mace_overall_iptwapplied_covariatesadjusted'},
     'pp2_itching_overall_iptwapplied_covariatesadjusted': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(age_65_YN) * C(group) + C(sex) + score_sum + C(atrial_fibrillation_YN) + C(cancer_YN) + C(cerebrovascular_disease_YN) + C(chronic_kidney_disease_YN) + C(chronic_liver_disease_YN) + C(chronic_respiratory_disease_YN) + C(coronary_artery_disease_YN) + C(depression_YN) + C(diabetes_mellitus_YN) + C(dyslipidemia_YN) + C(hearing_loss_YN) + C(hemiplegia_YN) + C(hypertension_YN) + C(insomnia_YN) + C(obstructive_sleep_apnea_YN) + C(parkinsons_disease_YN) + C(peptic_ulcer_YN) + C(peripheral_artery_disease_YN) + C(traumatic_head_injury_YN) + C(anti_parkinson_agents_YN) + C(anticoagulant_antiplatelet_YN) + C(antidepressants_YN) + C(antidiabetic_drugs_YN) + C(antihistamines_YN) + C(antipsychotics_YN) + C(antispasmodics_YN) + C(anxiolytics_YN) + C(bladder_antimuscarinics_YN) + C(h2ra_YN) + C(sedative_hypnotics_YN) + C(skeletal_muscle_relaxants_YN) + C(statins_YN)', 'ade_file': 'itching_df_260415.csv', 'iptw_file': 'pp2_overall_patients_with_propensity_scores.csv', 'result_file_name': 'pp2_itching_overall_iptwapplied_covariatesadjusted'},
    'pp2_urticaria_overall_iptwapplied_covariatesadjusted': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(age_65_YN) * C(group) + C(sex) + score_sum + C(atrial_fibrillation_YN) + C(cancer_YN) + C(cerebrovascular_disease_YN) + C(chronic_kidney_disease_YN) + C(chronic_liver_disease_YN) + C(chronic_respiratory_disease_YN) + C(coronary_artery_disease_YN) + C(depression_YN) + C(diabetes_mellitus_YN) + C(dyslipidemia_YN) + C(hearing_loss_YN) + C(hemiplegia_YN) + C(hypertension_YN) + C(insomnia_YN) + C(obstructive_sleep_apnea_YN) + C(parkinsons_disease_YN) + C(peptic_ulcer_YN) + C(peripheral_artery_disease_YN) + C(traumatic_head_injury_YN) + C(anti_parkinson_agents_YN) + C(anticoagulant_antiplatelet_YN) + C(antidepressants_YN) + C(antidiabetic_drugs_YN) + C(antihistamines_YN) + C(antipsychotics_YN) + C(antispasmodics_YN) + C(anxiolytics_YN) + C(bladder_antimuscarinics_YN) + C(h2ra_YN) + C(sedative_hypnotics_YN) + C(skeletal_muscle_relaxants_YN) + C(statins_YN)', 'ade_file': 'urticaria_df_260415.csv', 'iptw_file': 'pp2_overall_patients_with_propensity_scores.csv', 'result_file_name': 'pp2_aki_overall_iptwapplied_covariatesadjusted'},
     'pp2_aki_older_iptwapplied_crude': {'event_col': 'adverse_event_YN', 'tau': 4.0, 'rmst_formula': 'rmst_pseudo ~ C(group)', 'ade_file': 'aki_df_260415.csv', 'iptw_file': 'pp2_older_patients_with_propensity_scores.csv', 'result_file_name': 'pp2_aki_older_iptwapplied_crude'},
    'pp2_mace_older_iptwapplied_crude': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(group)', 'ade_file': 'mace_df_260415.csv', 'iptw_file': 'pp2_older_patients_with_propensity_scores.csv', 'result_file_name': 'pp2_mace_older_iptwapplied_crude'},
     'pp2_itching_older_iptwapplied_crude': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(group)', 'ade_file': 'itching_df_260415.csv', 'iptw_file': 'pp2_older_patients_with_propensity_scores.csv', 'result_file_name': 'pp2_itching_older_iptwapplied_crude'},
     'pp2_urticaria_older_iptwapplied_crude': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(group)', 'ade_file': 'urticaria_df_260415.csv', 'iptw_file': 'pp2_older_patients_with_propensity_scores.csv', 'result_file_name': 'pp2_aki_older_iptwapplied_crude'},
     'pp2_aki_younger_iptwapplied_crude': {'event_col': 'adverse_event_YN', 'tau': 4.0, 'rmst_formula': 'rmst_pseudo ~  C(group)', 'ade_file': 'aki_df_260415.csv', 'iptw_file': 'pp2_younger_patients_with_propensity_scores.csv', 'result_file_name': 'pp2_aki_younger_iptwapplied_crude'},
    'pp2_mace_younger_iptwapplied_crude': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(group)', 'ade_file': 'mace_df_260415.csv', 'iptw_file': 'pp2_younger_patients_with_propensity_scores.csv', 'result_file_name': 'pp2_mace_younger_iptwapplied_crude'},
     'pp2_itching_younger_iptwapplied_crude': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~  C(group)', 'ade_file': 'itching_df_260415.csv', 'iptw_file': 'pp2_younger_patients_with_propensity_scores.csv', 'result_file_name': 'pp2_itching_younger_iptwapplied_crude'},
    'pp2_urticaria_younger_iptwapplied_crude': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(group)', 'ade_file': 'urticaria_df_260415.csv', 'iptw_file': 'pp2_younger_patients_with_propensity_scores.csv', 'result_file_name': 'pp2_aki_younger_iptwapplied_crude'},
    'pp2_aki_overall_iptwapplied_crude': {'event_col': 'adverse_event_YN', 'tau': 4.0, 'rmst_formula': 'rmst_pseudo ~ C(age_65_YN) * C(group)', 'ade_file': 'aki_df_260415.csv', 'iptw_file': 'pp2_overall_patients_with_propensity_scores.csv', 'result_file_name': 'pp2_aki_overall_iptwapplied_crude'},
    'pp2_mace_overall_iptwapplied_crude': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(age_65_YN) * C(group)', 'ade_file': 'mace_df_260415.csv', 'iptw_file': 'pp2_overall_patients_with_propensity_scores.csv', 'result_file_name': 'pp2_mace_overall_iptwapplied_crude'},
     'pp2_itching_overall_iptwapplied_crude': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(age_65_YN) * C(group)', 'ade_file': 'itching_df_260415.csv', 'iptw_file': 'pp2_overall_patients_with_propensity_scores.csv', 'result_file_name': 'pp2_itching_overall_iptwapplied_crude'},
    'pp2_urticaria_overall_iptwapplied_crude': {'event_col': 'adverse_event_YN', 'tau': 6.0, 'rmst_formula': 'rmst_pseudo ~ C(age_65_YN) * C(group)', 'ade_file': 'urticaria_df_260415.csv', 'iptw_file': 'pp2_overall_patients_with_propensity_scores.csv', 'result_file_name': 'pp2_aki_overall_iptwapplied_crude'}
}

# ---------------------------------------------------------
# 2. THE FAST PSEUDO-VALUE GENERATOR (From previous step)
# ---------------------------------------------------------
def _calc_single_jackknife(i, durations, events, tau):
    dur_minus_i = np.delete(durations, i)
    eve_minus_i = np.delete(events, i)
    kmf = KaplanMeierFitter()
    kmf.fit(dur_minus_i, eve_minus_i)
    return restricted_mean_survival_time(kmf, t=tau)

def compute_pseudo_obs_fast(df, time_col, event_col, tau, n_jobs=-1):
    clean_df = df.reset_index(drop=True)
    n = len(clean_df)
    durations = clean_df[time_col].to_numpy()
    events = clean_df[event_col].to_numpy()
    
    kmf_full = KaplanMeierFitter()
    kmf_full.fit(durations, events)
    theta_full = restricted_mean_survival_time(kmf_full, t=tau)
    
    theta_minus_i_list = Parallel(n_jobs=n_jobs, prefer="threads")(
        delayed(_calc_single_jackknife)(i, durations, events, tau) for i in range(n)
    )
    
    pseudo_values = (n * theta_full) - ((n - 1) * np.array(theta_minus_i_list))
    return pd.Series(pseudo_values, index=df.index)

# ---------------------------------------------------------
# 3. THE AUTOMATION LOOP
# ---------------------------------------------------------
all_results = []

print("Starting Automated RMST Pipeline...")

for ade_name, config in ades_config.items():

    event_col = config['event_col']
    tau = config['tau']
    print(f"\n>>> Processing: {ade_name} (Tau = {tau} days) <<<")
    
    # Step A: Define formula uses the raw rmst_pseudo column now
    formula = config['rmst_formula']

    # Step B: Clean negative times for this specific run
    df = pd.read_csv(config['ade_file'], header=0, sep=',')
    iptw = pd.read_csv(config['iptw_file'], header=0, sep=',') 
    iptw_df=pd.merge(df[['person_id', 'age_65_YN', 'adverse_event_YN', 'search_start', 'end_date', 'max_ingredient_cnt', 'pp_group1', 'pp_group2']], iptw, how='inner', on='person_id')
    print(iptw_df)
    iptw_df['time']=(pd.to_datetime(iptw_df['end_date'])-pd.to_datetime(iptw_df['search_start'])).dt.days
    temp_df = iptw_df.copy()

    temp_df.loc[temp_df['time'] < 0, 'time'] = tau
    
    # Step C: Calculate Pseudo-values
    print("  - Calculating Pseudo-values...")
    temp_df['rmst_pseudo'] = compute_pseudo_obs_fast(temp_df, 'time', event_col, tau)
    
    # Step D: Add microscopic Jitter to prevent Singular Matrix / NaN SE errors
    np.random.seed(42)
    tiny_noise = np.random.normal(loc=0.0, scale=1e-5, size=len(temp_df))
    temp_df['rmst_pseudo_jittered'] = temp_df['rmst_pseudo'] + tiny_noise
    
    # Step E: Run the GLM
    print("  - Fitting Doubly Robust GLM...")
    model = smf.glm(formula=formula, 
                    data=temp_df, 
                    var_weights=temp_df['iptw'], 
                    family=sm.families.Gaussian())
    results = model.fit(cov_type='HC0')
    
    # Step F: Extract and format the results
    conf_int = results.conf_int()
    
    for term in results.params.index:
        row = {
            'Endpoint': ade_name,
            'Time Horizon (Tau)': tau,
            'Model Term': term,
            'Coefficient (Days)': results.params[term],
            'Lower 95% CI': conf_int.loc[term, 0],
            'Upper 95% CI': conf_int.loc[term, 1],
            'P-Value': results.pvalues[term]
        }

        all_results.append(row)

# ---------------------------------------------------------
# 4. EXPORT TO FILE
# ---------------------------------------------------------
final_results_df = pd.DataFrame(all_results)

# Export to CSV and Excel
csv_filename = "RMST_Multiple_Jittering_Endpoints_Results.csv"
excel_filename = "RMST_Multiple_Jittering_Endpoints_Results.xlsx"


final_results_df.to_csv(csv_filename, index=False)
final_results_df.to_excel(excel_filename, index=False)

print(f"\n✅ Pipeline Complete! Results saved to '{csv_filename}' and '{excel_filename}'.")
print(final_results_df.head(10).to_string(index=False))

